# Generated by Django 2.1 on 2018-10-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfeeder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='chip_id',
            field=models.CharField(max_length=32),
        ),
    ]
