"""
Django settings for petprototype project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'got)ifr#)fm3d$-^1m(9r(k4$ctmo%*7(o$jicj6y!2^rnoi*c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['ec2-13-57-38-126.us-west-1.compute.amazonaws.com']


# Application definition

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    )
}

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'petfeeder.apps.PetfeederConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'petprototype.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'petprototype.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'petprototype',
        'USER': 'petprototype',
        'PASSWORD': '123123',
        'HOST': 'localhost',
        'PORT': '25432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'


# Database Field Length Constants

UUID_LENGTH = 36

FOOD_BRAND_LENGTH = 50

PET_TYPE_LENGTH = 30

PET_BREED_LENGTH = 30

NAME_LENGTH = 30


# Database Field State Constants

REQUEST_COMPLETED = 0

REQUEST_STARTED = 1

REQUEST_IN_PROGRESS = 2

REQUEST_FAILED = 3

DISPENSE_TYPE = {
    'USER' : 1,     # User initiated request
    'AUTO' : 2,     # Automatically initiated request
}

REQUEST_TYPE = {
    'SETTINGS' : 1,
    'DISPENSE' : 2,
}


# MQTT Channels

FEEDER_PULL_CHANNEL = '/petprototype/feeder/pull/'

FEEDER_PUSH_CHANNEL = '/petprototype/feeder/push/'

FEEDER_PUSH_CHANNEL_ID = FEEDER_PUSH_CHANNEL + '{id}/'

DB_UPDATE_CHANNEL = '/petprototype/db/update/'


# MQTT Broker URL

MQTT_BROKER_ADDRESS = "ec2-13-57-38-126.us-west-1.compute.amazonaws.com"

MQTT_BROKER_PORT =  1883


# MQTT Function Ids

FEEDER_PUSH_FUNCTIONS = {
    "FEED" : "0001",     # bowl weight change
    "DISPENSE" : "0002", # dispense food
    "SYNC" : "0003",   # settings change
}

FEEDER_PULL_FUNCTIONS = {
    "" : "1001",
}

# MQTT Json Fields

OP_FIELD = "operation"
OPDATA_FIELD = "operation_data"
